Parameters:
  BucketName:
    Type: String
    Description: The name of the S3 bucket you want to create.

Resources:
  MyProdS3bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName

Outputs:
  S3BucketName:
    Description: The name of the S3 bucket created.
    Value: !Ref MyProdS3bucket